config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'events'  => 'events#index'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :invites
  resources :memberships
  resources :user_groups do
    resources :events
  end
  
  resources :invite_acceptance, only: [:edit]

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	has_many :memberships
    has_many :users, through: :memberships
    has_many :invites#, :class_name => "Invite", :foreign_key => 'user_group_id'
    has_many :events, inverse_of: :user_group, :dependent => :delete_all#, :class_name => "Event", :foreign_key => 'user_group_id'

    validates :name, presence: true, length: { maximum: 60 }, uniqueness: { case_sensitive: false }
    validates :user_id, presence: true

    accepts_nested_attributes_for :events
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]
  before_action :if_not_part_of_group, only: [:show, :edit, :update, :destroy]
  before_action :not_group_owner, only: [:destroy]
  #load_and_authorize_resource

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.paginate(page: params[:page])#.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
    @token = params[:accept_token]
    @group_owner = @user_group.users.where(id: @user_group.user_id).first
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
    @invite = Invite.new
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)
    respond_to do |format|
      if @user_group.save
        # create membership of owner of group
        group_owner = Membership.create(user_id: current_user.id, user_group_id: @user_group.id)
        group_owner.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:name, :user_id)
    end

    def if_not_part_of_group
      @user_membership = current_user.memberships.where(user_id: current_user.id, user_group_id: @user_group.id).first

      if !@user_membership && !current_user.admin?
        redirect_to user_groups_path
        flash[:danger] = "You are not member of this group"
      end
    end

    def not_group_owner
      if current_user.id != @user_group.user_id && !current_user.admin?
        redirect_to user_groups_path
        flash[:danger] = "You are not permitted to do this"
      end
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/_user_group.html.erb
    <li>
      	<%= link_to user_group.name, user_group %>
    </li>

app/views/user_groups/edit.html.erb
<%= form_for @invite , :url => invites_path do |f| %>
    <%= f.hidden_field :user_group_id, :value => @user_group.id %>
    <%= f.hidden_field :sender_id, :value => current_user.id %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.submit 'Send', class: "btn btn-primary btn-md" %>
<% end %>

app/views/user_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<div>
<ul class="users list-group"><% @user_groups.each do |user_group| %>
	<li class="list-group-item"><%= link_to user_group.name, user_group_path(user_group.id) %></li>
	<br />
</ul>
<% end %>
</div>
<br />
<div class="new_user_group">
	<%= link_to 'Create new group', new_user_group_path, class: "btn btn-primary" %>
</div>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

    <%= form_for(@user_group) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.submit "Create group", class: "btn btn-primary" %>

    <% end %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @user_group.name %></h1>
<p><b>Group owner:</b></p>
<div>
<p style="padding-left: 20px;"><%= link_to @group_owner.name, user_path(@group_owner.id, user_group_id: @user_group.id) %></p>
</div>
<p><b>Users:</b></p>
<div>
<% @user_group.users.each do |i| %>
	<ul class="users list-group">
		<% if i.id != @user_group.user_id%>
			<li class="list-group-item"><%= link_to i.name, user_path(i, user_group_id: @user_group.id)%></li>
		<% end %>
	</ul>
<% end %>
</div>
<br />
<%= link_to 'Events', user_group_events_path(@user_group.id), class: "btn btn-primary btn-md" %>
<%= link_to 'Send invitation', edit_user_group_path(@user_group), class: "btn btn-primary btn-md" %>
<% if current_user.admin? || current_user.id == @user_group.user_id %>
	<%= link_to "Delete", @user_group, :method=>:delete, :class=>:destroy, class: "btn btn-primary btn-md" %>
<% elsif ( !current_user.admin? || current_user.id != @user_group.user_id ) && @user_membership %>
	<%= link_to "Leave group", membership_path(@user_membership.id), :method=>:delete, :class=>:destroy, class: "btn btn-primary btn-md" %>
<% end %>
<%= link_to 'Back', user_groups_path, class: "btn btn-primary btn-md" %>