config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'events'  => 'events#index'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :invites
  resources :memberships
  resources :user_groups do
    resources :events
  end
  
  resources :invite_acceptance, only: [:edit]

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user_group
	#belongs_to :user

	# validates :user_group_id, presence: true
	# validates :creator_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :nil_global
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_user_group, only: [:new, :edit]
  before_action :get_id
  before_action :if_not_part_of_group
  before_action :not_creator, only: [:edit, :update, :destroy]


  # GET /events
  # GET /events.json
  def index
    @events = Event.where(user_group_id: $user_group_id)
    @group_name = UserGroup.find_by_id($user_group_id)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        #format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.html { redirect_to user_group_event_path(id: @event.id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: user_group_event(id: @event.id) }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to user_group_event_path(id: @event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to user_group_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_user_group
      @user_group = UserGroup.find_by_id(params[:user_group_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time, :user_group_id, :creator_id)
    end

    def get_id
      if !params[:user_group_id].nil?
        $user_group_id = params[:user_group_id]
      end
    end

    def if_not_part_of_group
      @user_membership = current_user.memberships.where(user_id: current_user.id, user_group_id: $user_group_id).first

      if !@user_membership && !current_user.admin?
        redirect_to user_group_path(id: $user_group_id)
        flash[:alert] = "You are not member of this group"
      end 
    end

    def not_creator
      if current_user.id != @event.creator_id && !current_user.admin?
        flash[:danger] = "You are not event creator"
        redirect_to :back
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for([@user_group, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>

  <%= f.hidden_field :user_group_id, :value => params[:user_group_id] %>
  <%= f.hidden_field :creator_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', user_group_event_path(id: @event.id) %> |
<%= link_to 'Back', user_group_events_path %>

app/views/events/index.html.erb
<% provide(:title, "Events") %>
<p id="notice"><%= notice %></p>

<h1><%= @group_name.name %> events</h1>

<br>

<%= link_to 'New Event', new_user_group_event_path, class: "btn btn-primary" %>
<br />

<br>

<div id='calendar'></div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', user_group_events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_user_group_event_path(id: @event.id), class: "btn btn-primary btn-sm" %>
<% if current_user.admin? || current_user.id == @event.creator_id %>
	<%= link_to "Delete", user_group_event_path(params[:user_group_id], @event), :confirm => "Are you sure you want to delete this event?", :method=>:delete, :class=>:destroy, class: "btn btn-primary btn-sm" %>
<% end %>
<%= link_to 'Back', user_group_events_path, class: "btn btn-primary btn-sm" %>